// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: vg.nat.istat.moji.deleteEmoji
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct DeleteEmoji<'a> {
    /// AT-URI of the emoji to delete
    #[serde(borrow)]
    pub uri: jacquard_common::types::string::AtUri<'a>,
}

pub mod delete_emoji_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Uri;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Uri = Unset;
    }
    ///State transition - sets the `uri` field to Set
    pub struct SetUri<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetUri<S> {}
    impl<S: State> State for SetUri<S> {
        type Uri = Set<members::uri>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `uri` field
        pub struct uri(());
    }
}

/// Builder for constructing an instance of this type
pub struct DeleteEmojiBuilder<'a, S: delete_emoji_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<jacquard_common::types::string::AtUri<'a>>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> DeleteEmoji<'a> {
    /// Create a new builder for this type
    pub fn new() -> DeleteEmojiBuilder<'a, delete_emoji_state::Empty> {
        DeleteEmojiBuilder::new()
    }
}

impl<'a> DeleteEmojiBuilder<'a, delete_emoji_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        DeleteEmojiBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None,),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> DeleteEmojiBuilder<'a, S>
where
    S: delete_emoji_state::State,
    S::Uri: delete_emoji_state::IsUnset,
{
    /// Set the `uri` field (required)
    pub fn uri(
        mut self,
        value: impl Into<jacquard_common::types::string::AtUri<'a>>,
    ) -> DeleteEmojiBuilder<'a, delete_emoji_state::SetUri<S>> {
        self.__unsafe_private_named.0 = ::core::option::Option::Some(value.into());
        DeleteEmojiBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> DeleteEmojiBuilder<'a, S>
where
    S: delete_emoji_state::State,
    S::Uri: delete_emoji_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> DeleteEmoji<'a> {
        DeleteEmoji {
            uri: self.__unsafe_private_named.0.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: std::collections::BTreeMap<
            jacquard_common::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> DeleteEmoji<'a> {
        DeleteEmoji {
            uri: self.__unsafe_private_named.0.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct DeleteEmojiOutput<'a> {
    pub success: bool,
}

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum DeleteEmojiError<'a> {
    /// User is not the owner or an admin
    #[serde(rename = "Unauthorized")]
    Unauthorized(std::option::Option<String>),
    /// Emoji not found
    #[serde(rename = "NotFound")]
    NotFound(std::option::Option<String>),
}

impl std::fmt::Display for DeleteEmojiError<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Unauthorized(msg) => {
                write!(f, "Unauthorized")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::NotFound(msg) => {
                write!(f, "NotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// Response type for
///vg.nat.istat.moji.deleteEmoji
pub struct DeleteEmojiResponse;
impl jacquard_common::xrpc::XrpcResp for DeleteEmojiResponse {
    const NSID: &'static str = "vg.nat.istat.moji.deleteEmoji";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = DeleteEmojiOutput<'de>;
    type Err<'de> = DeleteEmojiError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for DeleteEmoji<'a> {
    const NSID: &'static str = "vg.nat.istat.moji.deleteEmoji";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = DeleteEmojiResponse;
}

/// Endpoint type for
///vg.nat.istat.moji.deleteEmoji
pub struct DeleteEmojiRequest;
impl jacquard_common::xrpc::XrpcEndpoint for DeleteEmojiRequest {
    const PATH: &'static str = "/xrpc/vg.nat.istat.moji.deleteEmoji";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<'de> = DeleteEmoji<'de>;
    type Response = DeleteEmojiResponse;
}