// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: vg.nat.istat.moji.searchEmoji
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct EmojiView<'a> {
    /// Alt text description
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub alt_text: Option<jacquard_common::CowStr<'a>>,
    /// DID of the user who created this emoji
    #[serde(borrow)]
    pub created_by: jacquard_common::types::string::Did<'a>,
    /// Handle of the user who created this emoji
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub created_by_handle: Option<jacquard_common::types::string::Handle<'a>>,
    /// Canonical name of the emoji
    #[serde(borrow)]
    pub name: jacquard_common::CowStr<'a>,
    /// AT-URI of the emoji record
    #[serde(borrow)]
    pub uri: jacquard_common::types::string::AtUri<'a>,
    /// URL to the emoji image
    #[serde(borrow)]
    pub url: jacquard_common::CowStr<'a>,
}

pub mod emoji_view_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Uri;
        type Name;
        type Url;
        type CreatedBy;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Uri = Unset;
        type Name = Unset;
        type Url = Unset;
        type CreatedBy = Unset;
    }
    ///State transition - sets the `uri` field to Set
    pub struct SetUri<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetUri<S> {}
    impl<S: State> State for SetUri<S> {
        type Uri = Set<members::uri>;
        type Name = S::Name;
        type Url = S::Url;
        type CreatedBy = S::CreatedBy;
    }
    ///State transition - sets the `name` field to Set
    pub struct SetName<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetName<S> {}
    impl<S: State> State for SetName<S> {
        type Uri = S::Uri;
        type Name = Set<members::name>;
        type Url = S::Url;
        type CreatedBy = S::CreatedBy;
    }
    ///State transition - sets the `url` field to Set
    pub struct SetUrl<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetUrl<S> {}
    impl<S: State> State for SetUrl<S> {
        type Uri = S::Uri;
        type Name = S::Name;
        type Url = Set<members::url>;
        type CreatedBy = S::CreatedBy;
    }
    ///State transition - sets the `created_by` field to Set
    pub struct SetCreatedBy<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetCreatedBy<S> {}
    impl<S: State> State for SetCreatedBy<S> {
        type Uri = S::Uri;
        type Name = S::Name;
        type Url = S::Url;
        type CreatedBy = Set<members::created_by>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `uri` field
        pub struct uri(());
        ///Marker type for the `name` field
        pub struct name(());
        ///Marker type for the `url` field
        pub struct url(());
        ///Marker type for the `created_by` field
        pub struct created_by(());
    }
}

/// Builder for constructing an instance of this type
pub struct EmojiViewBuilder<'a, S: emoji_view_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<jacquard_common::types::string::Did<'a>>,
        ::core::option::Option<jacquard_common::types::string::Handle<'a>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<jacquard_common::types::string::AtUri<'a>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> EmojiView<'a> {
    /// Create a new builder for this type
    pub fn new() -> EmojiViewBuilder<'a, emoji_view_state::Empty> {
        EmojiViewBuilder::new()
    }
}

impl<'a> EmojiViewBuilder<'a, emoji_view_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        EmojiViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None, None, None, None, None, None),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S: emoji_view_state::State> EmojiViewBuilder<'a, S> {
    /// Set the `altText` field (optional)
    pub fn alt_text(
        mut self,
        value: impl Into<Option<jacquard_common::CowStr<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.0 = value.into();
        self
    }
    /// Set the `altText` field to an Option value (optional)
    pub fn maybe_alt_text(mut self, value: Option<jacquard_common::CowStr<'a>>) -> Self {
        self.__unsafe_private_named.0 = value;
        self
    }
}

impl<'a, S> EmojiViewBuilder<'a, S>
where
    S: emoji_view_state::State,
    S::CreatedBy: emoji_view_state::IsUnset,
{
    /// Set the `createdBy` field (required)
    pub fn created_by(
        mut self,
        value: impl Into<jacquard_common::types::string::Did<'a>>,
    ) -> EmojiViewBuilder<'a, emoji_view_state::SetCreatedBy<S>> {
        self.__unsafe_private_named.1 = ::core::option::Option::Some(value.into());
        EmojiViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S: emoji_view_state::State> EmojiViewBuilder<'a, S> {
    /// Set the `createdByHandle` field (optional)
    pub fn created_by_handle(
        mut self,
        value: impl Into<Option<jacquard_common::types::string::Handle<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.2 = value.into();
        self
    }
    /// Set the `createdByHandle` field to an Option value (optional)
    pub fn maybe_created_by_handle(
        mut self,
        value: Option<jacquard_common::types::string::Handle<'a>>,
    ) -> Self {
        self.__unsafe_private_named.2 = value;
        self
    }
}

impl<'a, S> EmojiViewBuilder<'a, S>
where
    S: emoji_view_state::State,
    S::Name: emoji_view_state::IsUnset,
{
    /// Set the `name` field (required)
    pub fn name(
        mut self,
        value: impl Into<jacquard_common::CowStr<'a>>,
    ) -> EmojiViewBuilder<'a, emoji_view_state::SetName<S>> {
        self.__unsafe_private_named.3 = ::core::option::Option::Some(value.into());
        EmojiViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> EmojiViewBuilder<'a, S>
where
    S: emoji_view_state::State,
    S::Uri: emoji_view_state::IsUnset,
{
    /// Set the `uri` field (required)
    pub fn uri(
        mut self,
        value: impl Into<jacquard_common::types::string::AtUri<'a>>,
    ) -> EmojiViewBuilder<'a, emoji_view_state::SetUri<S>> {
        self.__unsafe_private_named.4 = ::core::option::Option::Some(value.into());
        EmojiViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> EmojiViewBuilder<'a, S>
where
    S: emoji_view_state::State,
    S::Url: emoji_view_state::IsUnset,
{
    /// Set the `url` field (required)
    pub fn url(
        mut self,
        value: impl Into<jacquard_common::CowStr<'a>>,
    ) -> EmojiViewBuilder<'a, emoji_view_state::SetUrl<S>> {
        self.__unsafe_private_named.5 = ::core::option::Option::Some(value.into());
        EmojiViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> EmojiViewBuilder<'a, S>
where
    S: emoji_view_state::State,
    S::Uri: emoji_view_state::IsSet,
    S::Name: emoji_view_state::IsSet,
    S::Url: emoji_view_state::IsSet,
    S::CreatedBy: emoji_view_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> EmojiView<'a> {
        EmojiView {
            alt_text: self.__unsafe_private_named.0,
            created_by: self.__unsafe_private_named.1.unwrap(),
            created_by_handle: self.__unsafe_private_named.2,
            name: self.__unsafe_private_named.3.unwrap(),
            uri: self.__unsafe_private_named.4.unwrap(),
            url: self.__unsafe_private_named.5.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: std::collections::BTreeMap<
            jacquard_common::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> EmojiView<'a> {
        EmojiView {
            alt_text: self.__unsafe_private_named.0,
            created_by: self.__unsafe_private_named.1.unwrap(),
            created_by_handle: self.__unsafe_private_named.2,
            name: self.__unsafe_private_named.3.unwrap(),
            uri: self.__unsafe_private_named.4.unwrap(),
            url: self.__unsafe_private_named.5.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_vg_nat_istat_moji_searchEmoji() -> ::jacquard_lexicon::lexicon::LexiconDoc<
    'static,
> {
    ::jacquard_lexicon::lexicon::LexiconDoc {
        lexicon: ::jacquard_lexicon::lexicon::Lexicon::Lexicon1,
        id: ::jacquard_common::CowStr::new_static("vg.nat.istat.moji.searchEmoji"),
        revision: None,
        description: None,
        defs: {
            let mut map = ::std::collections::BTreeMap::new();
            map.insert(
                ::jacquard_common::smol_str::SmolStr::new_static("emojiView"),
                ::jacquard_lexicon::lexicon::LexUserType::Object(::jacquard_lexicon::lexicon::LexObject {
                    description: None,
                    required: Some(
                        vec![
                            ::jacquard_common::smol_str::SmolStr::new_static("uri"),
                            ::jacquard_common::smol_str::SmolStr::new_static("name"),
                            ::jacquard_common::smol_str::SmolStr::new_static("url"),
                            ::jacquard_common::smol_str::SmolStr::new_static("createdBy")
                        ],
                    ),
                    nullable: None,
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = ::std::collections::BTreeMap::new();
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("altText"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: Some(
                                    ::jacquard_common::CowStr::new_static(
                                        "Alt text description",
                                    ),
                                ),
                                format: None,
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static(
                                "createdBy",
                            ),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: Some(
                                    ::jacquard_common::CowStr::new_static(
                                        "DID of the user who created this emoji",
                                    ),
                                ),
                                format: Some(
                                    ::jacquard_lexicon::lexicon::LexStringFormat::Did,
                                ),
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static(
                                "createdByHandle",
                            ),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: Some(
                                    ::jacquard_common::CowStr::new_static(
                                        "Handle of the user who created this emoji",
                                    ),
                                ),
                                format: Some(
                                    ::jacquard_lexicon::lexicon::LexStringFormat::Handle,
                                ),
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("name"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: Some(
                                    ::jacquard_common::CowStr::new_static(
                                        "Canonical name of the emoji",
                                    ),
                                ),
                                format: None,
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("uri"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: Some(
                                    ::jacquard_common::CowStr::new_static(
                                        "AT-URI of the emoji record",
                                    ),
                                ),
                                format: Some(
                                    ::jacquard_lexicon::lexicon::LexStringFormat::AtUri,
                                ),
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("url"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: Some(
                                    ::jacquard_common::CowStr::new_static(
                                        "URL to the emoji image",
                                    ),
                                ),
                                format: None,
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map
                    },
                }),
            );
            map.insert(
                ::jacquard_common::smol_str::SmolStr::new_static("main"),
                ::jacquard_lexicon::lexicon::LexUserType::XrpcQuery(::jacquard_lexicon::lexicon::LexXrpcQuery {
                    description: None,
                    parameters: Some(
                        ::jacquard_lexicon::lexicon::LexXrpcQueryParameter::Params(::jacquard_lexicon::lexicon::LexXrpcParameters {
                            description: None,
                            required: Some(
                                vec![
                                    ::jacquard_common::smol_str::SmolStr::new_static("query")
                                ],
                            ),
                            properties: {
                                #[allow(unused_mut)]
                                let mut map = ::std::collections::BTreeMap::new();
                                map.insert(
                                    ::jacquard_common::smol_str::SmolStr::new_static("limit"),
                                    ::jacquard_lexicon::lexicon::LexXrpcParametersProperty::Integer(::jacquard_lexicon::lexicon::LexInteger {
                                        description: None,
                                        default: None,
                                        minimum: None,
                                        maximum: None,
                                        r#enum: None,
                                        r#const: None,
                                    }),
                                );
                                map.insert(
                                    ::jacquard_common::smol_str::SmolStr::new_static("query"),
                                    ::jacquard_lexicon::lexicon::LexXrpcParametersProperty::String(::jacquard_lexicon::lexicon::LexString {
                                        description: Some(
                                            ::jacquard_common::CowStr::new_static(
                                                "Search query to match against emoji name and alt text",
                                            ),
                                        ),
                                        format: None,
                                        default: None,
                                        min_length: None,
                                        max_length: None,
                                        min_graphemes: None,
                                        max_graphemes: None,
                                        r#enum: None,
                                        r#const: None,
                                        known_values: None,
                                    }),
                                );
                                map
                            },
                        }),
                    ),
                    output: None,
                    errors: None,
                }),
            );
            map
        },
    }
}

impl<'a> ::jacquard_lexicon::schema::LexiconSchema for EmojiView<'a> {
    fn nsid() -> &'static str {
        "vg.nat.istat.moji.searchEmoji"
    }
    fn def_name() -> &'static str {
        "emojiView"
    }
    fn lexicon_doc() -> ::jacquard_lexicon::lexicon::LexiconDoc<'static> {
        lexicon_doc_vg_nat_istat_moji_searchEmoji()
    }
    fn validate(
        &self,
    ) -> ::std::result::Result<(), ::jacquard_lexicon::validation::ConstraintError> {
        Ok(())
    }
}

#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct SearchEmoji<'a> {
    ///(default: 20, min: 1, max: 100)
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub limit: std::option::Option<i64>,
    #[serde(borrow)]
    pub query: jacquard_common::CowStr<'a>,
}

pub mod search_emoji_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Query;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Query = Unset;
    }
    ///State transition - sets the `query` field to Set
    pub struct SetQuery<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetQuery<S> {}
    impl<S: State> State for SetQuery<S> {
        type Query = Set<members::query>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `query` field
        pub struct query(());
    }
}

/// Builder for constructing an instance of this type
pub struct SearchEmojiBuilder<'a, S: search_emoji_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<i64>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> SearchEmoji<'a> {
    /// Create a new builder for this type
    pub fn new() -> SearchEmojiBuilder<'a, search_emoji_state::Empty> {
        SearchEmojiBuilder::new()
    }
}

impl<'a> SearchEmojiBuilder<'a, search_emoji_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        SearchEmojiBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None, None),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S: search_emoji_state::State> SearchEmojiBuilder<'a, S> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self.__unsafe_private_named.0 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self.__unsafe_private_named.0 = value;
        self
    }
}

impl<'a, S> SearchEmojiBuilder<'a, S>
where
    S: search_emoji_state::State,
    S::Query: search_emoji_state::IsUnset,
{
    /// Set the `query` field (required)
    pub fn query(
        mut self,
        value: impl Into<jacquard_common::CowStr<'a>>,
    ) -> SearchEmojiBuilder<'a, search_emoji_state::SetQuery<S>> {
        self.__unsafe_private_named.1 = ::core::option::Option::Some(value.into());
        SearchEmojiBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> SearchEmojiBuilder<'a, S>
where
    S: search_emoji_state::State,
    S::Query: search_emoji_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> SearchEmoji<'a> {
        SearchEmoji {
            limit: self.__unsafe_private_named.0,
            query: self.__unsafe_private_named.1.unwrap(),
        }
    }
}

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct SearchEmojiOutput<'a> {
    #[serde(borrow)]
    pub emojis: Vec<crate::vg_nat::istat::moji::search_emoji::EmojiView<'a>>,
}

/// Response type for
///vg.nat.istat.moji.searchEmoji
pub struct SearchEmojiResponse;
impl jacquard_common::xrpc::XrpcResp for SearchEmojiResponse {
    const NSID: &'static str = "vg.nat.istat.moji.searchEmoji";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = SearchEmojiOutput<'de>;
    type Err<'de> = jacquard_common::xrpc::GenericError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for SearchEmoji<'a> {
    const NSID: &'static str = "vg.nat.istat.moji.searchEmoji";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = SearchEmojiResponse;
}

/// Endpoint type for
///vg.nat.istat.moji.searchEmoji
pub struct SearchEmojiRequest;
impl jacquard_common::xrpc::XrpcEndpoint for SearchEmojiRequest {
    const PATH: &'static str = "/xrpc/vg.nat.istat.moji.searchEmoji";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<'de> = SearchEmoji<'de>;
    type Response = SearchEmojiResponse;
}