// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: vg.nat.istat.moderation.blacklistCid
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic,
    Default
)]
#[serde(rename_all = "camelCase")]
pub struct BlacklistCid<'a> {
    /// The CID to blacklist
    #[serde(borrow)]
    pub cid: jacquard_common::CowStr<'a>,
    /// Type of content being blacklisted
    #[serde(borrow)]
    pub content_type: jacquard_common::CowStr<'a>,
    /// Predefined reason for blacklisting
    #[serde(borrow)]
    pub reason: jacquard_common::CowStr<'a>,
    /// Additional details explaining the blacklist reason
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub reason_details: std::option::Option<jacquard_common::CowStr<'a>>,
}

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct BlacklistCidOutput<'a> {
    pub success: bool,
}

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum BlacklistCidError<'a> {
    /// User is not an admin
    #[serde(rename = "Unauthorized")]
    Unauthorized(std::option::Option<String>),
    /// This CID is already blacklisted
    #[serde(rename = "AlreadyBlacklisted")]
    AlreadyBlacklisted(std::option::Option<String>),
}

impl std::fmt::Display for BlacklistCidError<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Unauthorized(msg) => {
                write!(f, "Unauthorized")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::AlreadyBlacklisted(msg) => {
                write!(f, "AlreadyBlacklisted")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// Response type for
///vg.nat.istat.moderation.blacklistCid
pub struct BlacklistCidResponse;
impl jacquard_common::xrpc::XrpcResp for BlacklistCidResponse {
    const NSID: &'static str = "vg.nat.istat.moderation.blacklistCid";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = BlacklistCidOutput<'de>;
    type Err<'de> = BlacklistCidError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for BlacklistCid<'a> {
    const NSID: &'static str = "vg.nat.istat.moderation.blacklistCid";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = BlacklistCidResponse;
}

/// Endpoint type for
///vg.nat.istat.moderation.blacklistCid
pub struct BlacklistCidRequest;
impl jacquard_common::xrpc::XrpcEndpoint for BlacklistCidRequest {
    const PATH: &'static str = "/xrpc/vg.nat.istat.moderation.blacklistCid";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<'de> = BlacklistCid<'de>;
    type Response = BlacklistCidResponse;
}