// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: vg.nat.istat.moderation.isAdmin
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct IsAdminOutput<'a> {
    /// Whether the current user is an admin
    pub is_admin: bool,
}

/// XRPC request marker type
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    serde::Serialize,
    serde::Deserialize,
    jacquard_derive::IntoStatic
)]
pub struct IsAdmin;
/// Response type for
///vg.nat.istat.moderation.isAdmin
pub struct IsAdminResponse;
impl jacquard_common::xrpc::XrpcResp for IsAdminResponse {
    const NSID: &'static str = "vg.nat.istat.moderation.isAdmin";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = IsAdminOutput<'de>;
    type Err<'de> = jacquard_common::xrpc::GenericError<'de>;
}

impl jacquard_common::xrpc::XrpcRequest for IsAdmin {
    const NSID: &'static str = "vg.nat.istat.moderation.isAdmin";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = IsAdminResponse;
}

/// Endpoint type for
///vg.nat.istat.moderation.isAdmin
pub struct IsAdminRequest;
impl jacquard_common::xrpc::XrpcEndpoint for IsAdminRequest {
    const PATH: &'static str = "/xrpc/vg.nat.istat.moderation.isAdmin";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<'de> = IsAdmin;
    type Response = IsAdminResponse;
}