// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: vg.nat.istat.moderation.listAuditLog
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct AuditLogEntry<'a> {
    /// The moderation action performed
    #[serde(borrow)]
    pub action: jacquard_common::CowStr<'a>,
    /// When this action was performed
    pub created_at: jacquard_common::types::string::Datetime,
    /// Unique identifier for this log entry
    pub id: i64,
    /// DID of the moderator who performed the action
    #[serde(borrow)]
    pub moderator_did: jacquard_common::types::string::Did<'a>,
    /// Handle of the moderator (for display)
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub moderator_handle: Option<jacquard_common::types::string::Handle<'a>>,
    /// Reason for the action (for blacklists)
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub reason: Option<jacquard_common::CowStr<'a>>,
    /// Additional details about the reason
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub reason_details: Option<jacquard_common::CowStr<'a>>,
    /// Identifier of the targeted content (CID or AT-URI)
    #[serde(borrow)]
    pub target_id: jacquard_common::CowStr<'a>,
    /// Type of content targeted
    #[serde(borrow)]
    pub target_type: jacquard_common::CowStr<'a>,
}

pub mod audit_log_entry_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Id;
        type ModeratorDid;
        type Action;
        type TargetType;
        type TargetId;
        type CreatedAt;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Id = Unset;
        type ModeratorDid = Unset;
        type Action = Unset;
        type TargetType = Unset;
        type TargetId = Unset;
        type CreatedAt = Unset;
    }
    ///State transition - sets the `id` field to Set
    pub struct SetId<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetId<S> {}
    impl<S: State> State for SetId<S> {
        type Id = Set<members::id>;
        type ModeratorDid = S::ModeratorDid;
        type Action = S::Action;
        type TargetType = S::TargetType;
        type TargetId = S::TargetId;
        type CreatedAt = S::CreatedAt;
    }
    ///State transition - sets the `moderator_did` field to Set
    pub struct SetModeratorDid<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetModeratorDid<S> {}
    impl<S: State> State for SetModeratorDid<S> {
        type Id = S::Id;
        type ModeratorDid = Set<members::moderator_did>;
        type Action = S::Action;
        type TargetType = S::TargetType;
        type TargetId = S::TargetId;
        type CreatedAt = S::CreatedAt;
    }
    ///State transition - sets the `action` field to Set
    pub struct SetAction<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetAction<S> {}
    impl<S: State> State for SetAction<S> {
        type Id = S::Id;
        type ModeratorDid = S::ModeratorDid;
        type Action = Set<members::action>;
        type TargetType = S::TargetType;
        type TargetId = S::TargetId;
        type CreatedAt = S::CreatedAt;
    }
    ///State transition - sets the `target_type` field to Set
    pub struct SetTargetType<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetTargetType<S> {}
    impl<S: State> State for SetTargetType<S> {
        type Id = S::Id;
        type ModeratorDid = S::ModeratorDid;
        type Action = S::Action;
        type TargetType = Set<members::target_type>;
        type TargetId = S::TargetId;
        type CreatedAt = S::CreatedAt;
    }
    ///State transition - sets the `target_id` field to Set
    pub struct SetTargetId<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetTargetId<S> {}
    impl<S: State> State for SetTargetId<S> {
        type Id = S::Id;
        type ModeratorDid = S::ModeratorDid;
        type Action = S::Action;
        type TargetType = S::TargetType;
        type TargetId = Set<members::target_id>;
        type CreatedAt = S::CreatedAt;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetCreatedAt<S> {}
    impl<S: State> State for SetCreatedAt<S> {
        type Id = S::Id;
        type ModeratorDid = S::ModeratorDid;
        type Action = S::Action;
        type TargetType = S::TargetType;
        type TargetId = S::TargetId;
        type CreatedAt = Set<members::created_at>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `id` field
        pub struct id(());
        ///Marker type for the `moderator_did` field
        pub struct moderator_did(());
        ///Marker type for the `action` field
        pub struct action(());
        ///Marker type for the `target_type` field
        pub struct target_type(());
        ///Marker type for the `target_id` field
        pub struct target_id(());
        ///Marker type for the `created_at` field
        pub struct created_at(());
    }
}

/// Builder for constructing an instance of this type
pub struct AuditLogEntryBuilder<'a, S: audit_log_entry_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<jacquard_common::types::string::Datetime>,
        ::core::option::Option<i64>,
        ::core::option::Option<jacquard_common::types::string::Did<'a>>,
        ::core::option::Option<jacquard_common::types::string::Handle<'a>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> AuditLogEntry<'a> {
    /// Create a new builder for this type
    pub fn new() -> AuditLogEntryBuilder<'a, audit_log_entry_state::Empty> {
        AuditLogEntryBuilder::new()
    }
}

impl<'a> AuditLogEntryBuilder<'a, audit_log_entry_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        AuditLogEntryBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
            ),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> AuditLogEntryBuilder<'a, S>
where
    S: audit_log_entry_state::State,
    S::Action: audit_log_entry_state::IsUnset,
{
    /// Set the `action` field (required)
    pub fn action(
        mut self,
        value: impl Into<jacquard_common::CowStr<'a>>,
    ) -> AuditLogEntryBuilder<'a, audit_log_entry_state::SetAction<S>> {
        self.__unsafe_private_named.0 = ::core::option::Option::Some(value.into());
        AuditLogEntryBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> AuditLogEntryBuilder<'a, S>
where
    S: audit_log_entry_state::State,
    S::CreatedAt: audit_log_entry_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<jacquard_common::types::string::Datetime>,
    ) -> AuditLogEntryBuilder<'a, audit_log_entry_state::SetCreatedAt<S>> {
        self.__unsafe_private_named.1 = ::core::option::Option::Some(value.into());
        AuditLogEntryBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> AuditLogEntryBuilder<'a, S>
where
    S: audit_log_entry_state::State,
    S::Id: audit_log_entry_state::IsUnset,
{
    /// Set the `id` field (required)
    pub fn id(
        mut self,
        value: impl Into<i64>,
    ) -> AuditLogEntryBuilder<'a, audit_log_entry_state::SetId<S>> {
        self.__unsafe_private_named.2 = ::core::option::Option::Some(value.into());
        AuditLogEntryBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> AuditLogEntryBuilder<'a, S>
where
    S: audit_log_entry_state::State,
    S::ModeratorDid: audit_log_entry_state::IsUnset,
{
    /// Set the `moderatorDid` field (required)
    pub fn moderator_did(
        mut self,
        value: impl Into<jacquard_common::types::string::Did<'a>>,
    ) -> AuditLogEntryBuilder<'a, audit_log_entry_state::SetModeratorDid<S>> {
        self.__unsafe_private_named.3 = ::core::option::Option::Some(value.into());
        AuditLogEntryBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S: audit_log_entry_state::State> AuditLogEntryBuilder<'a, S> {
    /// Set the `moderatorHandle` field (optional)
    pub fn moderator_handle(
        mut self,
        value: impl Into<Option<jacquard_common::types::string::Handle<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.4 = value.into();
        self
    }
    /// Set the `moderatorHandle` field to an Option value (optional)
    pub fn maybe_moderator_handle(
        mut self,
        value: Option<jacquard_common::types::string::Handle<'a>>,
    ) -> Self {
        self.__unsafe_private_named.4 = value;
        self
    }
}

impl<'a, S: audit_log_entry_state::State> AuditLogEntryBuilder<'a, S> {
    /// Set the `reason` field (optional)
    pub fn reason(
        mut self,
        value: impl Into<Option<jacquard_common::CowStr<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.5 = value.into();
        self
    }
    /// Set the `reason` field to an Option value (optional)
    pub fn maybe_reason(mut self, value: Option<jacquard_common::CowStr<'a>>) -> Self {
        self.__unsafe_private_named.5 = value;
        self
    }
}

impl<'a, S: audit_log_entry_state::State> AuditLogEntryBuilder<'a, S> {
    /// Set the `reasonDetails` field (optional)
    pub fn reason_details(
        mut self,
        value: impl Into<Option<jacquard_common::CowStr<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.6 = value.into();
        self
    }
    /// Set the `reasonDetails` field to an Option value (optional)
    pub fn maybe_reason_details(
        mut self,
        value: Option<jacquard_common::CowStr<'a>>,
    ) -> Self {
        self.__unsafe_private_named.6 = value;
        self
    }
}

impl<'a, S> AuditLogEntryBuilder<'a, S>
where
    S: audit_log_entry_state::State,
    S::TargetId: audit_log_entry_state::IsUnset,
{
    /// Set the `targetId` field (required)
    pub fn target_id(
        mut self,
        value: impl Into<jacquard_common::CowStr<'a>>,
    ) -> AuditLogEntryBuilder<'a, audit_log_entry_state::SetTargetId<S>> {
        self.__unsafe_private_named.7 = ::core::option::Option::Some(value.into());
        AuditLogEntryBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> AuditLogEntryBuilder<'a, S>
where
    S: audit_log_entry_state::State,
    S::TargetType: audit_log_entry_state::IsUnset,
{
    /// Set the `targetType` field (required)
    pub fn target_type(
        mut self,
        value: impl Into<jacquard_common::CowStr<'a>>,
    ) -> AuditLogEntryBuilder<'a, audit_log_entry_state::SetTargetType<S>> {
        self.__unsafe_private_named.8 = ::core::option::Option::Some(value.into());
        AuditLogEntryBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> AuditLogEntryBuilder<'a, S>
where
    S: audit_log_entry_state::State,
    S::Id: audit_log_entry_state::IsSet,
    S::ModeratorDid: audit_log_entry_state::IsSet,
    S::Action: audit_log_entry_state::IsSet,
    S::TargetType: audit_log_entry_state::IsSet,
    S::TargetId: audit_log_entry_state::IsSet,
    S::CreatedAt: audit_log_entry_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> AuditLogEntry<'a> {
        AuditLogEntry {
            action: self.__unsafe_private_named.0.unwrap(),
            created_at: self.__unsafe_private_named.1.unwrap(),
            id: self.__unsafe_private_named.2.unwrap(),
            moderator_did: self.__unsafe_private_named.3.unwrap(),
            moderator_handle: self.__unsafe_private_named.4,
            reason: self.__unsafe_private_named.5,
            reason_details: self.__unsafe_private_named.6,
            target_id: self.__unsafe_private_named.7.unwrap(),
            target_type: self.__unsafe_private_named.8.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: std::collections::BTreeMap<
            jacquard_common::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> AuditLogEntry<'a> {
        AuditLogEntry {
            action: self.__unsafe_private_named.0.unwrap(),
            created_at: self.__unsafe_private_named.1.unwrap(),
            id: self.__unsafe_private_named.2.unwrap(),
            moderator_did: self.__unsafe_private_named.3.unwrap(),
            moderator_handle: self.__unsafe_private_named.4,
            reason: self.__unsafe_private_named.5,
            reason_details: self.__unsafe_private_named.6,
            target_id: self.__unsafe_private_named.7.unwrap(),
            target_type: self.__unsafe_private_named.8.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_vg_nat_istat_moderation_listAuditLog() -> ::jacquard_lexicon::lexicon::LexiconDoc<
    'static,
> {
    ::jacquard_lexicon::lexicon::LexiconDoc {
        lexicon: ::jacquard_lexicon::lexicon::Lexicon::Lexicon1,
        id: ::jacquard_common::CowStr::new_static(
            "vg.nat.istat.moderation.listAuditLog",
        ),
        revision: None,
        description: None,
        defs: {
            let mut map = ::std::collections::BTreeMap::new();
            map.insert(
                ::jacquard_common::smol_str::SmolStr::new_static("auditLogEntry"),
                ::jacquard_lexicon::lexicon::LexUserType::Object(::jacquard_lexicon::lexicon::LexObject {
                    description: None,
                    required: Some(
                        vec![
                            ::jacquard_common::smol_str::SmolStr::new_static("id"),
                            ::jacquard_common::smol_str::SmolStr::new_static("moderatorDid"),
                            ::jacquard_common::smol_str::SmolStr::new_static("action"),
                            ::jacquard_common::smol_str::SmolStr::new_static("targetType"),
                            ::jacquard_common::smol_str::SmolStr::new_static("targetId"),
                            ::jacquard_common::smol_str::SmolStr::new_static("createdAt")
                        ],
                    ),
                    nullable: None,
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = ::std::collections::BTreeMap::new();
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("action"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: Some(
                                    ::jacquard_common::CowStr::new_static(
                                        "The moderation action performed",
                                    ),
                                ),
                                format: None,
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static(
                                "createdAt",
                            ),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: Some(
                                    ::jacquard_common::CowStr::new_static(
                                        "When this action was performed",
                                    ),
                                ),
                                format: Some(
                                    ::jacquard_lexicon::lexicon::LexStringFormat::Datetime,
                                ),
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("id"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::Integer(::jacquard_lexicon::lexicon::LexInteger {
                                description: None,
                                default: None,
                                minimum: None,
                                maximum: None,
                                r#enum: None,
                                r#const: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static(
                                "moderatorDid",
                            ),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: Some(
                                    ::jacquard_common::CowStr::new_static(
                                        "DID of the moderator who performed the action",
                                    ),
                                ),
                                format: Some(
                                    ::jacquard_lexicon::lexicon::LexStringFormat::Did,
                                ),
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static(
                                "moderatorHandle",
                            ),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: Some(
                                    ::jacquard_common::CowStr::new_static(
                                        "Handle of the moderator (for display)",
                                    ),
                                ),
                                format: Some(
                                    ::jacquard_lexicon::lexicon::LexStringFormat::Handle,
                                ),
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("reason"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: Some(
                                    ::jacquard_common::CowStr::new_static(
                                        "Reason for the action (for blacklists)",
                                    ),
                                ),
                                format: None,
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static(
                                "reasonDetails",
                            ),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: Some(
                                    ::jacquard_common::CowStr::new_static(
                                        "Additional details about the reason",
                                    ),
                                ),
                                format: None,
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("targetId"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: Some(
                                    ::jacquard_common::CowStr::new_static(
                                        "Identifier of the targeted content (CID or AT-URI)",
                                    ),
                                ),
                                format: None,
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static(
                                "targetType",
                            ),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: Some(
                                    ::jacquard_common::CowStr::new_static(
                                        "Type of content targeted",
                                    ),
                                ),
                                format: None,
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map
                    },
                }),
            );
            map.insert(
                ::jacquard_common::smol_str::SmolStr::new_static("main"),
                ::jacquard_lexicon::lexicon::LexUserType::XrpcQuery(::jacquard_lexicon::lexicon::LexXrpcQuery {
                    description: None,
                    parameters: Some(
                        ::jacquard_lexicon::lexicon::LexXrpcQueryParameter::Params(::jacquard_lexicon::lexicon::LexXrpcParameters {
                            description: None,
                            required: None,
                            properties: {
                                #[allow(unused_mut)]
                                let mut map = ::std::collections::BTreeMap::new();
                                map.insert(
                                    ::jacquard_common::smol_str::SmolStr::new_static("cursor"),
                                    ::jacquard_lexicon::lexicon::LexXrpcParametersProperty::String(::jacquard_lexicon::lexicon::LexString {
                                        description: Some(
                                            ::jacquard_common::CowStr::new_static("Pagination cursor"),
                                        ),
                                        format: None,
                                        default: None,
                                        min_length: None,
                                        max_length: None,
                                        min_graphemes: None,
                                        max_graphemes: None,
                                        r#enum: None,
                                        r#const: None,
                                        known_values: None,
                                    }),
                                );
                                map.insert(
                                    ::jacquard_common::smol_str::SmolStr::new_static("limit"),
                                    ::jacquard_lexicon::lexicon::LexXrpcParametersProperty::Integer(::jacquard_lexicon::lexicon::LexInteger {
                                        description: None,
                                        default: None,
                                        minimum: None,
                                        maximum: None,
                                        r#enum: None,
                                        r#const: None,
                                    }),
                                );
                                map
                            },
                        }),
                    ),
                    output: None,
                    errors: None,
                }),
            );
            map
        },
    }
}

impl<'a> ::jacquard_lexicon::schema::LexiconSchema for AuditLogEntry<'a> {
    fn nsid() -> &'static str {
        "vg.nat.istat.moderation.listAuditLog"
    }
    fn def_name() -> &'static str {
        "auditLogEntry"
    }
    fn lexicon_doc() -> ::jacquard_lexicon::lexicon::LexiconDoc<'static> {
        lexicon_doc_vg_nat_istat_moderation_listAuditLog()
    }
    fn validate(
        &self,
    ) -> ::std::result::Result<(), ::jacquard_lexicon::validation::ConstraintError> {
        Ok(())
    }
}

#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct ListAuditLog<'a> {
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub cursor: std::option::Option<jacquard_common::CowStr<'a>>,
    ///(default: 50, min: 1, max: 100)
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub limit: std::option::Option<i64>,
}

pub mod list_audit_log_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {}
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {}
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {}
}

/// Builder for constructing an instance of this type
pub struct ListAuditLogBuilder<'a, S: list_audit_log_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<i64>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> ListAuditLog<'a> {
    /// Create a new builder for this type
    pub fn new() -> ListAuditLogBuilder<'a, list_audit_log_state::Empty> {
        ListAuditLogBuilder::new()
    }
}

impl<'a> ListAuditLogBuilder<'a, list_audit_log_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        ListAuditLogBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None, None),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S: list_audit_log_state::State> ListAuditLogBuilder<'a, S> {
    /// Set the `cursor` field (optional)
    pub fn cursor(
        mut self,
        value: impl Into<Option<jacquard_common::CowStr<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.0 = value.into();
        self
    }
    /// Set the `cursor` field to an Option value (optional)
    pub fn maybe_cursor(mut self, value: Option<jacquard_common::CowStr<'a>>) -> Self {
        self.__unsafe_private_named.0 = value;
        self
    }
}

impl<'a, S: list_audit_log_state::State> ListAuditLogBuilder<'a, S> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self.__unsafe_private_named.1 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self.__unsafe_private_named.1 = value;
        self
    }
}

impl<'a, S> ListAuditLogBuilder<'a, S>
where
    S: list_audit_log_state::State,
{
    /// Build the final struct
    pub fn build(self) -> ListAuditLog<'a> {
        ListAuditLog {
            cursor: self.__unsafe_private_named.0,
            limit: self.__unsafe_private_named.1,
        }
    }
}

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct ListAuditLogOutput<'a> {
    /// Pagination cursor for next page
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub cursor: std::option::Option<jacquard_common::CowStr<'a>>,
    #[serde(borrow)]
    pub entries: Vec<
        crate::vg_nat::istat::moderation::list_audit_log::AuditLogEntry<'a>,
    >,
}

/// Response type for
///vg.nat.istat.moderation.listAuditLog
pub struct ListAuditLogResponse;
impl jacquard_common::xrpc::XrpcResp for ListAuditLogResponse {
    const NSID: &'static str = "vg.nat.istat.moderation.listAuditLog";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = ListAuditLogOutput<'de>;
    type Err<'de> = jacquard_common::xrpc::GenericError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for ListAuditLog<'a> {
    const NSID: &'static str = "vg.nat.istat.moderation.listAuditLog";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = ListAuditLogResponse;
}

/// Endpoint type for
///vg.nat.istat.moderation.listAuditLog
pub struct ListAuditLogRequest;
impl jacquard_common::xrpc::XrpcEndpoint for ListAuditLogRequest {
    const PATH: &'static str = "/xrpc/vg.nat.istat.moderation.listAuditLog";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<'de> = ListAuditLog<'de>;
    type Response = ListAuditLogResponse;
}