// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: vg.nat.istat.moderation.listBlacklisted
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct BlacklistedCidView<'a> {
    /// When this was blacklisted
    pub blacklisted_at: jacquard_common::types::string::Datetime,
    /// The blacklisted CID
    #[serde(borrow)]
    pub cid: jacquard_common::CowStr<'a>,
    /// Type of content
    #[serde(borrow)]
    pub content_type: jacquard_common::CowStr<'a>,
    /// DID of the moderator who blacklisted this
    #[serde(borrow)]
    pub moderator_did: jacquard_common::types::string::Did<'a>,
    /// Reason for blacklisting
    #[serde(borrow)]
    pub reason: jacquard_common::CowStr<'a>,
    /// Additional details about the blacklist
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub reason_details: Option<jacquard_common::CowStr<'a>>,
}

pub mod blacklisted_cid_view_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Cid;
        type Reason;
        type ContentType;
        type ModeratorDid;
        type BlacklistedAt;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Cid = Unset;
        type Reason = Unset;
        type ContentType = Unset;
        type ModeratorDid = Unset;
        type BlacklistedAt = Unset;
    }
    ///State transition - sets the `cid` field to Set
    pub struct SetCid<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetCid<S> {}
    impl<S: State> State for SetCid<S> {
        type Cid = Set<members::cid>;
        type Reason = S::Reason;
        type ContentType = S::ContentType;
        type ModeratorDid = S::ModeratorDid;
        type BlacklistedAt = S::BlacklistedAt;
    }
    ///State transition - sets the `reason` field to Set
    pub struct SetReason<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetReason<S> {}
    impl<S: State> State for SetReason<S> {
        type Cid = S::Cid;
        type Reason = Set<members::reason>;
        type ContentType = S::ContentType;
        type ModeratorDid = S::ModeratorDid;
        type BlacklistedAt = S::BlacklistedAt;
    }
    ///State transition - sets the `content_type` field to Set
    pub struct SetContentType<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetContentType<S> {}
    impl<S: State> State for SetContentType<S> {
        type Cid = S::Cid;
        type Reason = S::Reason;
        type ContentType = Set<members::content_type>;
        type ModeratorDid = S::ModeratorDid;
        type BlacklistedAt = S::BlacklistedAt;
    }
    ///State transition - sets the `moderator_did` field to Set
    pub struct SetModeratorDid<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetModeratorDid<S> {}
    impl<S: State> State for SetModeratorDid<S> {
        type Cid = S::Cid;
        type Reason = S::Reason;
        type ContentType = S::ContentType;
        type ModeratorDid = Set<members::moderator_did>;
        type BlacklistedAt = S::BlacklistedAt;
    }
    ///State transition - sets the `blacklisted_at` field to Set
    pub struct SetBlacklistedAt<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetBlacklistedAt<S> {}
    impl<S: State> State for SetBlacklistedAt<S> {
        type Cid = S::Cid;
        type Reason = S::Reason;
        type ContentType = S::ContentType;
        type ModeratorDid = S::ModeratorDid;
        type BlacklistedAt = Set<members::blacklisted_at>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `cid` field
        pub struct cid(());
        ///Marker type for the `reason` field
        pub struct reason(());
        ///Marker type for the `content_type` field
        pub struct content_type(());
        ///Marker type for the `moderator_did` field
        pub struct moderator_did(());
        ///Marker type for the `blacklisted_at` field
        pub struct blacklisted_at(());
    }
}

/// Builder for constructing an instance of this type
pub struct BlacklistedCidViewBuilder<'a, S: blacklisted_cid_view_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<jacquard_common::types::string::Datetime>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<jacquard_common::types::string::Did<'a>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> BlacklistedCidView<'a> {
    /// Create a new builder for this type
    pub fn new() -> BlacklistedCidViewBuilder<'a, blacklisted_cid_view_state::Empty> {
        BlacklistedCidViewBuilder::new()
    }
}

impl<'a> BlacklistedCidViewBuilder<'a, blacklisted_cid_view_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        BlacklistedCidViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None, None, None, None, None, None),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> BlacklistedCidViewBuilder<'a, S>
where
    S: blacklisted_cid_view_state::State,
    S::BlacklistedAt: blacklisted_cid_view_state::IsUnset,
{
    /// Set the `blacklistedAt` field (required)
    pub fn blacklisted_at(
        mut self,
        value: impl Into<jacquard_common::types::string::Datetime>,
    ) -> BlacklistedCidViewBuilder<'a, blacklisted_cid_view_state::SetBlacklistedAt<S>> {
        self.__unsafe_private_named.0 = ::core::option::Option::Some(value.into());
        BlacklistedCidViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> BlacklistedCidViewBuilder<'a, S>
where
    S: blacklisted_cid_view_state::State,
    S::Cid: blacklisted_cid_view_state::IsUnset,
{
    /// Set the `cid` field (required)
    pub fn cid(
        mut self,
        value: impl Into<jacquard_common::CowStr<'a>>,
    ) -> BlacklistedCidViewBuilder<'a, blacklisted_cid_view_state::SetCid<S>> {
        self.__unsafe_private_named.1 = ::core::option::Option::Some(value.into());
        BlacklistedCidViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> BlacklistedCidViewBuilder<'a, S>
where
    S: blacklisted_cid_view_state::State,
    S::ContentType: blacklisted_cid_view_state::IsUnset,
{
    /// Set the `contentType` field (required)
    pub fn content_type(
        mut self,
        value: impl Into<jacquard_common::CowStr<'a>>,
    ) -> BlacklistedCidViewBuilder<'a, blacklisted_cid_view_state::SetContentType<S>> {
        self.__unsafe_private_named.2 = ::core::option::Option::Some(value.into());
        BlacklistedCidViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> BlacklistedCidViewBuilder<'a, S>
where
    S: blacklisted_cid_view_state::State,
    S::ModeratorDid: blacklisted_cid_view_state::IsUnset,
{
    /// Set the `moderatorDid` field (required)
    pub fn moderator_did(
        mut self,
        value: impl Into<jacquard_common::types::string::Did<'a>>,
    ) -> BlacklistedCidViewBuilder<'a, blacklisted_cid_view_state::SetModeratorDid<S>> {
        self.__unsafe_private_named.3 = ::core::option::Option::Some(value.into());
        BlacklistedCidViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> BlacklistedCidViewBuilder<'a, S>
where
    S: blacklisted_cid_view_state::State,
    S::Reason: blacklisted_cid_view_state::IsUnset,
{
    /// Set the `reason` field (required)
    pub fn reason(
        mut self,
        value: impl Into<jacquard_common::CowStr<'a>>,
    ) -> BlacklistedCidViewBuilder<'a, blacklisted_cid_view_state::SetReason<S>> {
        self.__unsafe_private_named.4 = ::core::option::Option::Some(value.into());
        BlacklistedCidViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S: blacklisted_cid_view_state::State> BlacklistedCidViewBuilder<'a, S> {
    /// Set the `reasonDetails` field (optional)
    pub fn reason_details(
        mut self,
        value: impl Into<Option<jacquard_common::CowStr<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.5 = value.into();
        self
    }
    /// Set the `reasonDetails` field to an Option value (optional)
    pub fn maybe_reason_details(
        mut self,
        value: Option<jacquard_common::CowStr<'a>>,
    ) -> Self {
        self.__unsafe_private_named.5 = value;
        self
    }
}

impl<'a, S> BlacklistedCidViewBuilder<'a, S>
where
    S: blacklisted_cid_view_state::State,
    S::Cid: blacklisted_cid_view_state::IsSet,
    S::Reason: blacklisted_cid_view_state::IsSet,
    S::ContentType: blacklisted_cid_view_state::IsSet,
    S::ModeratorDid: blacklisted_cid_view_state::IsSet,
    S::BlacklistedAt: blacklisted_cid_view_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> BlacklistedCidView<'a> {
        BlacklistedCidView {
            blacklisted_at: self.__unsafe_private_named.0.unwrap(),
            cid: self.__unsafe_private_named.1.unwrap(),
            content_type: self.__unsafe_private_named.2.unwrap(),
            moderator_did: self.__unsafe_private_named.3.unwrap(),
            reason: self.__unsafe_private_named.4.unwrap(),
            reason_details: self.__unsafe_private_named.5,
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: std::collections::BTreeMap<
            jacquard_common::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> BlacklistedCidView<'a> {
        BlacklistedCidView {
            blacklisted_at: self.__unsafe_private_named.0.unwrap(),
            cid: self.__unsafe_private_named.1.unwrap(),
            content_type: self.__unsafe_private_named.2.unwrap(),
            moderator_did: self.__unsafe_private_named.3.unwrap(),
            reason: self.__unsafe_private_named.4.unwrap(),
            reason_details: self.__unsafe_private_named.5,
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_vg_nat_istat_moderation_listBlacklisted() -> ::jacquard_lexicon::lexicon::LexiconDoc<
    'static,
> {
    ::jacquard_lexicon::lexicon::LexiconDoc {
        lexicon: ::jacquard_lexicon::lexicon::Lexicon::Lexicon1,
        id: ::jacquard_common::CowStr::new_static(
            "vg.nat.istat.moderation.listBlacklisted",
        ),
        revision: None,
        description: None,
        defs: {
            let mut map = ::std::collections::BTreeMap::new();
            map.insert(
                ::jacquard_common::smol_str::SmolStr::new_static("blacklistedCidView"),
                ::jacquard_lexicon::lexicon::LexUserType::Object(::jacquard_lexicon::lexicon::LexObject {
                    description: None,
                    required: Some(
                        vec![
                            ::jacquard_common::smol_str::SmolStr::new_static("cid"),
                            ::jacquard_common::smol_str::SmolStr::new_static("reason"),
                            ::jacquard_common::smol_str::SmolStr::new_static("contentType"),
                            ::jacquard_common::smol_str::SmolStr::new_static("moderatorDid"),
                            ::jacquard_common::smol_str::SmolStr::new_static("blacklistedAt")
                        ],
                    ),
                    nullable: None,
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = ::std::collections::BTreeMap::new();
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static(
                                "blacklistedAt",
                            ),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: Some(
                                    ::jacquard_common::CowStr::new_static(
                                        "When this was blacklisted",
                                    ),
                                ),
                                format: Some(
                                    ::jacquard_lexicon::lexicon::LexStringFormat::Datetime,
                                ),
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("cid"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: Some(
                                    ::jacquard_common::CowStr::new_static("The blacklisted CID"),
                                ),
                                format: None,
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static(
                                "contentType",
                            ),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: Some(
                                    ::jacquard_common::CowStr::new_static("Type of content"),
                                ),
                                format: None,
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static(
                                "moderatorDid",
                            ),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: Some(
                                    ::jacquard_common::CowStr::new_static(
                                        "DID of the moderator who blacklisted this",
                                    ),
                                ),
                                format: Some(
                                    ::jacquard_lexicon::lexicon::LexStringFormat::Did,
                                ),
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("reason"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: Some(
                                    ::jacquard_common::CowStr::new_static(
                                        "Reason for blacklisting",
                                    ),
                                ),
                                format: None,
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static(
                                "reasonDetails",
                            ),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: Some(
                                    ::jacquard_common::CowStr::new_static(
                                        "Additional details about the blacklist",
                                    ),
                                ),
                                format: None,
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map
                    },
                }),
            );
            map.insert(
                ::jacquard_common::smol_str::SmolStr::new_static("main"),
                ::jacquard_lexicon::lexicon::LexUserType::XrpcQuery(::jacquard_lexicon::lexicon::LexXrpcQuery {
                    description: None,
                    parameters: Some(
                        ::jacquard_lexicon::lexicon::LexXrpcQueryParameter::Params(::jacquard_lexicon::lexicon::LexXrpcParameters {
                            description: None,
                            required: None,
                            properties: {
                                #[allow(unused_mut)]
                                let mut map = ::std::collections::BTreeMap::new();
                                map.insert(
                                    ::jacquard_common::smol_str::SmolStr::new_static(
                                        "contentType",
                                    ),
                                    ::jacquard_lexicon::lexicon::LexXrpcParametersProperty::String(::jacquard_lexicon::lexicon::LexString {
                                        description: Some(
                                            ::jacquard_common::CowStr::new_static(
                                                "Filter by content type",
                                            ),
                                        ),
                                        format: None,
                                        default: None,
                                        min_length: None,
                                        max_length: None,
                                        min_graphemes: None,
                                        max_graphemes: None,
                                        r#enum: None,
                                        r#const: None,
                                        known_values: None,
                                    }),
                                );
                                map.insert(
                                    ::jacquard_common::smol_str::SmolStr::new_static("limit"),
                                    ::jacquard_lexicon::lexicon::LexXrpcParametersProperty::Integer(::jacquard_lexicon::lexicon::LexInteger {
                                        description: None,
                                        default: None,
                                        minimum: None,
                                        maximum: None,
                                        r#enum: None,
                                        r#const: None,
                                    }),
                                );
                                map
                            },
                        }),
                    ),
                    output: None,
                    errors: None,
                }),
            );
            map
        },
    }
}

impl<'a> ::jacquard_lexicon::schema::LexiconSchema for BlacklistedCidView<'a> {
    fn nsid() -> &'static str {
        "vg.nat.istat.moderation.listBlacklisted"
    }
    fn def_name() -> &'static str {
        "blacklistedCidView"
    }
    fn lexicon_doc() -> ::jacquard_lexicon::lexicon::LexiconDoc<'static> {
        lexicon_doc_vg_nat_istat_moderation_listBlacklisted()
    }
    fn validate(
        &self,
    ) -> ::std::result::Result<(), ::jacquard_lexicon::validation::ConstraintError> {
        Ok(())
    }
}

#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct ListBlacklisted<'a> {
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub content_type: std::option::Option<jacquard_common::CowStr<'a>>,
    ///(default: 50, min: 1, max: 100)
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub limit: std::option::Option<i64>,
}

pub mod list_blacklisted_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {}
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {}
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {}
}

/// Builder for constructing an instance of this type
pub struct ListBlacklistedBuilder<'a, S: list_blacklisted_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<i64>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> ListBlacklisted<'a> {
    /// Create a new builder for this type
    pub fn new() -> ListBlacklistedBuilder<'a, list_blacklisted_state::Empty> {
        ListBlacklistedBuilder::new()
    }
}

impl<'a> ListBlacklistedBuilder<'a, list_blacklisted_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        ListBlacklistedBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None, None),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S: list_blacklisted_state::State> ListBlacklistedBuilder<'a, S> {
    /// Set the `contentType` field (optional)
    pub fn content_type(
        mut self,
        value: impl Into<Option<jacquard_common::CowStr<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.0 = value.into();
        self
    }
    /// Set the `contentType` field to an Option value (optional)
    pub fn maybe_content_type(
        mut self,
        value: Option<jacquard_common::CowStr<'a>>,
    ) -> Self {
        self.__unsafe_private_named.0 = value;
        self
    }
}

impl<'a, S: list_blacklisted_state::State> ListBlacklistedBuilder<'a, S> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self.__unsafe_private_named.1 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self.__unsafe_private_named.1 = value;
        self
    }
}

impl<'a, S> ListBlacklistedBuilder<'a, S>
where
    S: list_blacklisted_state::State,
{
    /// Build the final struct
    pub fn build(self) -> ListBlacklisted<'a> {
        ListBlacklisted {
            content_type: self.__unsafe_private_named.0,
            limit: self.__unsafe_private_named.1,
        }
    }
}

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct ListBlacklistedOutput<'a> {
    #[serde(borrow)]
    pub blacklisted: Vec<
        crate::vg_nat::istat::moderation::list_blacklisted::BlacklistedCidView<'a>,
    >,
}

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum ListBlacklistedError<'a> {
    /// User is not an admin
    #[serde(rename = "Unauthorized")]
    Unauthorized(std::option::Option<String>),
}

impl std::fmt::Display for ListBlacklistedError<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Unauthorized(msg) => {
                write!(f, "Unauthorized")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// Response type for
///vg.nat.istat.moderation.listBlacklisted
pub struct ListBlacklistedResponse;
impl jacquard_common::xrpc::XrpcResp for ListBlacklistedResponse {
    const NSID: &'static str = "vg.nat.istat.moderation.listBlacklisted";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = ListBlacklistedOutput<'de>;
    type Err<'de> = ListBlacklistedError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for ListBlacklisted<'a> {
    const NSID: &'static str = "vg.nat.istat.moderation.listBlacklisted";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = ListBlacklistedResponse;
}

/// Endpoint type for
///vg.nat.istat.moderation.listBlacklisted
pub struct ListBlacklistedRequest;
impl jacquard_common::xrpc::XrpcEndpoint for ListBlacklistedRequest {
    const PATH: &'static str = "/xrpc/vg.nat.istat.moderation.listBlacklisted";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<'de> = ListBlacklisted<'de>;
    type Response = ListBlacklistedResponse;
}