// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: vg.nat.istat.moderation.removeBlacklist
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic,
    Default
)]
#[serde(rename_all = "camelCase")]
pub struct RemoveBlacklist<'a> {
    /// The CID to remove from blacklist
    #[serde(borrow)]
    pub cid: jacquard_common::CowStr<'a>,
}

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct RemoveBlacklistOutput<'a> {
    pub success: bool,
}

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum RemoveBlacklistError<'a> {
    /// User is not an admin
    #[serde(rename = "Unauthorized")]
    Unauthorized(std::option::Option<String>),
    /// This CID is not blacklisted
    #[serde(rename = "NotFound")]
    NotFound(std::option::Option<String>),
}

impl std::fmt::Display for RemoveBlacklistError<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Unauthorized(msg) => {
                write!(f, "Unauthorized")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::NotFound(msg) => {
                write!(f, "NotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// Response type for
///vg.nat.istat.moderation.removeBlacklist
pub struct RemoveBlacklistResponse;
impl jacquard_common::xrpc::XrpcResp for RemoveBlacklistResponse {
    const NSID: &'static str = "vg.nat.istat.moderation.removeBlacklist";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = RemoveBlacklistOutput<'de>;
    type Err<'de> = RemoveBlacklistError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for RemoveBlacklist<'a> {
    const NSID: &'static str = "vg.nat.istat.moderation.removeBlacklist";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = RemoveBlacklistResponse;
}

/// Endpoint type for
///vg.nat.istat.moderation.removeBlacklist
pub struct RemoveBlacklistRequest;
impl jacquard_common::xrpc::XrpcEndpoint for RemoveBlacklistRequest {
    const PATH: &'static str = "/xrpc/vg.nat.istat.moderation.removeBlacklist";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<'de> = RemoveBlacklist<'de>;
    type Response = RemoveBlacklistResponse;
}