// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: vg.nat.istat.status.getStatus
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct GetStatus<'a> {
    #[serde(borrow)]
    pub handle: jacquard_common::types::string::Handle<'a>,
    #[serde(borrow)]
    pub rkey: jacquard_common::CowStr<'a>,
}

pub mod get_status_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Handle;
        type Rkey;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Handle = Unset;
        type Rkey = Unset;
    }
    ///State transition - sets the `handle` field to Set
    pub struct SetHandle<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetHandle<S> {}
    impl<S: State> State for SetHandle<S> {
        type Handle = Set<members::handle>;
        type Rkey = S::Rkey;
    }
    ///State transition - sets the `rkey` field to Set
    pub struct SetRkey<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetRkey<S> {}
    impl<S: State> State for SetRkey<S> {
        type Handle = S::Handle;
        type Rkey = Set<members::rkey>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `handle` field
        pub struct handle(());
        ///Marker type for the `rkey` field
        pub struct rkey(());
    }
}

/// Builder for constructing an instance of this type
pub struct GetStatusBuilder<'a, S: get_status_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<jacquard_common::types::string::Handle<'a>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> GetStatus<'a> {
    /// Create a new builder for this type
    pub fn new() -> GetStatusBuilder<'a, get_status_state::Empty> {
        GetStatusBuilder::new()
    }
}

impl<'a> GetStatusBuilder<'a, get_status_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        GetStatusBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None, None),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> GetStatusBuilder<'a, S>
where
    S: get_status_state::State,
    S::Handle: get_status_state::IsUnset,
{
    /// Set the `handle` field (required)
    pub fn handle(
        mut self,
        value: impl Into<jacquard_common::types::string::Handle<'a>>,
    ) -> GetStatusBuilder<'a, get_status_state::SetHandle<S>> {
        self.__unsafe_private_named.0 = ::core::option::Option::Some(value.into());
        GetStatusBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> GetStatusBuilder<'a, S>
where
    S: get_status_state::State,
    S::Rkey: get_status_state::IsUnset,
{
    /// Set the `rkey` field (required)
    pub fn rkey(
        mut self,
        value: impl Into<jacquard_common::CowStr<'a>>,
    ) -> GetStatusBuilder<'a, get_status_state::SetRkey<S>> {
        self.__unsafe_private_named.1 = ::core::option::Option::Some(value.into());
        GetStatusBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> GetStatusBuilder<'a, S>
where
    S: get_status_state::State,
    S::Handle: get_status_state::IsSet,
    S::Rkey: get_status_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> GetStatus<'a> {
        GetStatus {
            handle: self.__unsafe_private_named.0.unwrap(),
            rkey: self.__unsafe_private_named.1.unwrap(),
        }
    }
}

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct GetStatusOutput<'a> {
    /// When this status was created
    pub created_at: jacquard_common::types::string::Datetime,
    /// Optional status text description
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub description: std::option::Option<jacquard_common::CowStr<'a>>,
    /// a URL to the emoji
    #[serde(borrow)]
    pub emoji_url: jacquard_common::CowStr<'a>,
    /// Optional expiration timestamp for this status
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub expires: std::option::Option<jacquard_common::types::string::Datetime>,
    /// Optional status text title
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub title: std::option::Option<jacquard_common::CowStr<'a>>,
}

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum GetStatusError<'a> {
    /// The requested status does not exist
    #[serde(rename = "StatusNotFound")]
    StatusNotFound(std::option::Option<String>),
}

impl std::fmt::Display for GetStatusError<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::StatusNotFound(msg) => {
                write!(f, "StatusNotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// Response type for
///vg.nat.istat.status.getStatus
pub struct GetStatusResponse;
impl jacquard_common::xrpc::XrpcResp for GetStatusResponse {
    const NSID: &'static str = "vg.nat.istat.status.getStatus";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = GetStatusOutput<'de>;
    type Err<'de> = GetStatusError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for GetStatus<'a> {
    const NSID: &'static str = "vg.nat.istat.status.getStatus";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetStatusResponse;
}

/// Endpoint type for
///vg.nat.istat.status.getStatus
pub struct GetStatusRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetStatusRequest {
    const PATH: &'static str = "/xrpc/vg.nat.istat.status.getStatus";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<'de> = GetStatus<'de>;
    type Response = GetStatusResponse;
}