// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: vg.nat.istat.status.listUserStatuses
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct ListUserStatuses<'a> {
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub cursor: std::option::Option<jacquard_common::CowStr<'a>>,
    #[serde(borrow)]
    pub handle: jacquard_common::types::string::Handle<'a>,
    ///(default: 50, min: 1, max: 100)
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub limit: std::option::Option<i64>,
}

pub mod list_user_statuses_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Handle;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Handle = Unset;
    }
    ///State transition - sets the `handle` field to Set
    pub struct SetHandle<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetHandle<S> {}
    impl<S: State> State for SetHandle<S> {
        type Handle = Set<members::handle>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `handle` field
        pub struct handle(());
    }
}

/// Builder for constructing an instance of this type
pub struct ListUserStatusesBuilder<'a, S: list_user_statuses_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<jacquard_common::types::string::Handle<'a>>,
        ::core::option::Option<i64>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> ListUserStatuses<'a> {
    /// Create a new builder for this type
    pub fn new() -> ListUserStatusesBuilder<'a, list_user_statuses_state::Empty> {
        ListUserStatusesBuilder::new()
    }
}

impl<'a> ListUserStatusesBuilder<'a, list_user_statuses_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        ListUserStatusesBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None, None, None),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S: list_user_statuses_state::State> ListUserStatusesBuilder<'a, S> {
    /// Set the `cursor` field (optional)
    pub fn cursor(
        mut self,
        value: impl Into<Option<jacquard_common::CowStr<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.0 = value.into();
        self
    }
    /// Set the `cursor` field to an Option value (optional)
    pub fn maybe_cursor(mut self, value: Option<jacquard_common::CowStr<'a>>) -> Self {
        self.__unsafe_private_named.0 = value;
        self
    }
}

impl<'a, S> ListUserStatusesBuilder<'a, S>
where
    S: list_user_statuses_state::State,
    S::Handle: list_user_statuses_state::IsUnset,
{
    /// Set the `handle` field (required)
    pub fn handle(
        mut self,
        value: impl Into<jacquard_common::types::string::Handle<'a>>,
    ) -> ListUserStatusesBuilder<'a, list_user_statuses_state::SetHandle<S>> {
        self.__unsafe_private_named.1 = ::core::option::Option::Some(value.into());
        ListUserStatusesBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S: list_user_statuses_state::State> ListUserStatusesBuilder<'a, S> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self.__unsafe_private_named.2 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self.__unsafe_private_named.2 = value;
        self
    }
}

impl<'a, S> ListUserStatusesBuilder<'a, S>
where
    S: list_user_statuses_state::State,
    S::Handle: list_user_statuses_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> ListUserStatuses<'a> {
        ListUserStatuses {
            cursor: self.__unsafe_private_named.0,
            handle: self.__unsafe_private_named.1.unwrap(),
            limit: self.__unsafe_private_named.2,
        }
    }
}

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct ListUserStatusesOutput<'a> {
    /// Pagination cursor for next page
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub cursor: std::option::Option<jacquard_common::CowStr<'a>>,
    #[serde(borrow)]
    pub statuses: Vec<jacquard_common::types::value::Data<'a>>,
}

/// Response type for
///vg.nat.istat.status.listUserStatuses
pub struct ListUserStatusesResponse;
impl jacquard_common::xrpc::XrpcResp for ListUserStatusesResponse {
    const NSID: &'static str = "vg.nat.istat.status.listUserStatuses";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = ListUserStatusesOutput<'de>;
    type Err<'de> = jacquard_common::xrpc::GenericError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for ListUserStatuses<'a> {
    const NSID: &'static str = "vg.nat.istat.status.listUserStatuses";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = ListUserStatusesResponse;
}

/// Endpoint type for
///vg.nat.istat.status.listUserStatuses
pub struct ListUserStatusesRequest;
impl jacquard_common::xrpc::XrpcEndpoint for ListUserStatusesRequest {
    const PATH: &'static str = "/xrpc/vg.nat.istat.status.listUserStatuses";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<'de> = ListUserStatuses<'de>;
    type Response = ListUserStatusesResponse;
}